services:
  - type: web
    name: johnbox
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PUBLIC_URL
        value: https://johnbox.onrender.com
